### ISSUE TITLE
Is it possible to use jquery plugins or some bootstrap components with widok?

### ISSUE THREAD

**Issue by freewind** [widok/widok#37]
Is it possible to integrate this: https://github.com/jonmiles/bootstrap-treeview ?

**Comment by tindzk** [comment]
Yes. You can use external libraries. All you need to do is set the ID of the widget. In ``render()`` you can then access it using jQuery. Also have a look at the Scala.js bindings for jQuery.

**Comment by freewind** [comment]
Can I still use `channels` or `vars` and have the bi-binding working as well?

**Comment by tindzk** [comment]
The easiest would be to generate the tree by iterating over a ``Buffer``. Then, you don't even need any third-party libraries. Bidirectional binding only makes sense for input fields anyway.

**Comment by freewind** [comment]
Yes, it's possible to generate the tree with a `Buffer`, since my requirement is not complex.

I also want it to have these functionalities:

1. click on the node, it will become a input, allows editing
2. drag a node up or down, to sort them
3. drag a node to become the child of another node

Maybe `bi-binding` is useful for implementing them.

Could you recommend some ideas of doing it all by widok? I just knew widok several days ago, not familiar enough.

**Comment by tindzk** [comment]
Drag-and-drop is not implemented yet, but if you need it quickly, you can add the respective events here and submit a pull request: https://github.com/widok/widok/blob/master/js/src/main/scala/org/widok/Widget.scala#L262. For the input field, just use ``show()`` which you pass a ``Var`` that is ``false`` by default. For an example, see https://github.com/widok/todomvc/blob/master/src/main/scala/org/widok/todomvc/Application.scala

**Comment by freewind** [comment]
Working on this. Give me several days before I can create a pull request

**Comment by tindzk** [comment]
Actually, I already implemented it a few days ago. To try it out, please follow [this tutorial](https://github.com/widok/widok/blob/master/docs/chapters/09-developing.md#compilation).

**Comment by freewind** [comment]
Thanks @tindzk ! 

I made a pull request https://github.com/widok/widok/pull/40 to complete the missing drag & drop events based on your latest code, and also a demo project: https://github.com/freewind/widok-drag-and-drop

I really appreciate if you could find anything can be improved in the code: https://github.com/freewind/widok-drag-and-drop/blob/master/src/main/scala/example/Main.scala

(I can make the demo working, but not feel that's the best solution)

**Comment by tindzk** [comment]
Thank you for your contributions. I have several suggestions:

For convenience, you may want to use ``Opt[T]`` instead of ``Var[Option[T]]``. Then you could write:

```scala
userOnDragging := user
userOnDragging.clear()
```

Instead of:

```scala
userOnDragging := Some(user)
userOnDragging := None
```

When creating custom widgets, I'd try not to access the outer scope. This prevents the widget of being reused in other parts of your application.

When using your DnD-aware image widget (``MyImage``), I would refrain from calling low-level methods like ``onDragStart`` or ``onDragEnd``. You already do the processing to detect the current state (``dragging``) in ``MyImage``. There would be nothing wrong with exposing ``dragging`` like this:

```scala
def isDragging: ReadChannel[Boolean] = dragging
```

In reactive programming, it's all about expressing your program as composable streams. With ``isDragging`` you can change ``toImage`` as follows:

```scala
def toImage(src: String) = {
  val image = new MyImage(src)
  image.isDragging.attach(
    if (_) userOnDragging := user
    else   userOnDragging.clear()
  )
  image
}
```

Some of the members of ``User`` are subject to changes. Instead of replacing the whole row, I usually find it easier to use channels for changeable members in the class declaration:

```scala
case class User(name: Var[String], image: Opt[String])
```

This is also more efficient as it won't need to re-render the entire row, just the value which was changed. It also increases the readability, because you don't need to use ``replace()`` with ``copy()``:

```scala
for {
  draggingU <- userOnDragging.get
  if draggingU != user
} {
  users.replace(user, user.copy(image = draggingU.image))
  users.replace(draggingU, draggingU.copy(image = None))
}
```

This would become:

```scala
if (!userOnDragging.contains$(user)) {
  val src = userOnDragging.get
  user.image := src.image.get
  src.image.clear()
}
```

You should have a look at [RxJS](http://xgrommx.github.io/rx-book/) and see how DnD is done there. I've seen in the past that they were using ``takeUntil`` for dealing with mouse movements (like [here](https://gist.github.com/mattpodwysocki/2156153)), without maintaining any temporary state variables. I'm pretty sure something similar could be done here as well. Let me know if there are any missing combinators in ``Channel`` that would be necessary for this.

**Comment by freewind** [comment]
I can't say more thanks! I'll rewrite my code following your suggestions, thanks very much!

**Comment by freewind** [comment]
I just modified my code based on your suggestions, almost good, except that when I drag the image into another div, the source images wont't be removed(You can see two images there). But if you drag the first one again, it will report an error in chrome console: `java.util.NoSuchElementException: None.get`. I'm not sure where is wrong.

You can see latest code here: https://github.com/freewind/widok-drag-and-drop/blob/master/src/main/scala/example/Main.scala

**Comment by tindzk** [comment]
I see. The reason is that ``Opt`` will only propagate a value when there is one. Note that ``Opt[T]`` implements ``ReadChannel[T]`` and not ``ReadChannel[Option[T]]``. In your case you need the latter, i.e., you want to find out when the value is cleared. To do this, just use the method ``values`` and replace the image by an empty ``span`` if the current value is ``None``.

**Comment by freewind** [comment]
Get it, thanks again @tindzk ! :+1: 

I think I can start using widok to write some more applications now
