### ISSUE TITLE
Let `buffer.flatMap` accept `Option`?

### ISSUE THREAD

**Issue by freewind** [widok/widok#44]
This is a simplified code which I want to use `flatMap` and `Option` arguments.

```scala
val countries = Buffer[Country]()
countries.flatMap { country =>
    if(theCountryIsMatchedKeyword(country)) {
         Some(country)
    } else {
         None
    }
}
```

It's not compilable because `flatMap`'s signature is:

     def flatMap[U](f: T => ReadBuffer[U]): ReadBuffer[U] = ...

It requires `T => ReadBuffer[U]`.

Is it possible to provide a normal `flatMap` that I can pass in a `T => Option[U]` or `def flatMap[B, That](f: A => GenTraversableOnce[B])(implicit bf: CanBuildFrom[Repr, B, That])`.

(In the above code it seems I can use `filter` directly, but is not easy in my real code)

**Comment by tindzk** [comment]
Instead of returning ``Some(country)`` and ``None``, you could also return ``Buffer(country)`` and ``Buffer()``.

``flatMap()`` cannot be overloaded, but we could add a method ``flatMapSeq()`` that takes a ``Seq[T]`` instead of a ``ReadBuffer[T]``. This makes the interface more consistent with ``Channel`` which provides the same method as well.

The only caveat would be that ``Option`` doesn't implement the ``Seq`` trait. I'm somewhat reluctant to using ``GenTraversableOnce`` which in my opinion only entails unnecessary complexity.
