### ISSUE TITLE
For div re-render based on one or several channels

### ISSUE THREAD

**Issue by freewind** [widok/widok#45]
There is some kind of code from my project simplified as:

```scala
val showBackupFiles: Var[Boolean] = Var(false)
def getFiles:Seq[File] = if(showBackupFiles.get) backupFiles else workingFiles

override def view(): View = {
  div(checkbox().bind(showBackupFiles)),
  div(getFiles.map(div(_.toString))
}
```

The above code is not working well, that no matter I checked the checkbox or not, the files won't change.

The correct way may be:

```scala
val showBackupFiles: Var[Boolean] = Var(false)
def getFiles(showBackup):Seq[File] = if(showBackup) backupFiles else workingFiles

override def view(): View = {
  div(checkbox().bind(showBackupFiles)),
  showBackupFiles.map(b => div(getFiles(b).map(div(_.toString)))
}
```

This is working well, but I have to put `showBackupFiles` outside the `div`, which makes it hard to see the html structure.

I wonder if it's possible I can write it like:

```scala
val showBackupFiles: Var[Boolean] = Var(false)
def getFiles:Seq[File] = if(showBackupFiles.get) backupFiles else workingFiles

override def view(): View = {
  div(checkbox().bind(showBackupFiles)),
  div(getFiles.map(div(_.toString)).triggeredBy(showBackupFiles)
}
```

Notice the fake `triggeredBy` method.

And what if a div is based on multiple channels? Like:

```scala
val showBackupFiles1: Var[Boolean] = Var(false)
val showBackupFiles2: Var[Boolean] = Var(false)
val showBackupFiles3: Var[Boolean] = Var(false)
```
I can't find an easy way to write it correctly:

```scala
def getFiles(b1:Boolean, b2:Boolean, b3:Boolean) :Seq[File] = {
    if(b1) backupFiles1 
    else if(b2) backupFiles2 
    else if(b3) backupFiles3 
    else  workingFiles
}

override def view(): View = {
  div(checkbox().bind(showBackupFiles)),
  showBackupFiles1.map(b1 => 
    showBackupFiles2.map(b2 => 
      showBackupFiles3.map(b3 => 
        div(getFiles(b1,b2,b3).map(div(_.toString)))))
}
```

But with the `triggeredBy`, I might write it like:

```
def getFiles:Seq[File] = {
    if(showBackupFiles1.get) backupFiles1 
    else if(showBackupFiles2.get) backupFiles2 
    else if(showBackupFiles3.get) backupFiles3 
    else  workingFiles
}

override def view(): View = {
  div(checkbox().bind(showBackupFiles)),
  div(getFiles.map(div(_.toString)).triggeredBy(showBackupFiles1, showBackupFiles2, showBackupFiles3)
}
```

I'm not sure if there is already some good solutions, or if my understand about widok is correct.

Thanks for your continuous helps!

**Comment by tindzk** [comment]
Interesting suggestion. Usually, when observing streams you actually want to know the values that are being produced. ``triggeredBy`` will be only useful if you want to refresh the content of a widget whenever a channel produces a value. I believe there's little benefit to adding ``triggeredBy``, but perhaps you can come up with a more convincing use case.

I would structure your concrete example differently:

```scala
val showBackupFiles = Var(false)
def backupFiles()   = div("...")
def workingFiles()  = div("...")

def view() = Inline(
  div(checkbox().bind(showBackupFiles)),
  div(
  	showBackupFiles.map(
  	  if (_) backupFiles()
  	  else   workingFiles()
    )
  )
)
```

It is a good idea to use functions for partials because they make the code more informative and you can potentially re-use these in other parts of your program. Also, they prevent that you're nesting too deeply.

Considering that you want to observe multiple channels at the same time, you can write (``|`` is an alias for ``merge``):

```scala
val showBackupFiles1: Var[Boolean] = Var(false)
val showBackupFiles2: Var[Boolean] = Var(false)
val showBackupFiles3: Var[Boolean] = Var(false)

val ch: ReadChannel[Boolean] =
  showBackupFiles1 | showBackupFiles2 | showBackupFiles3
```


But obviously you will lose the information on which channel the particular values were produced.

**Comment by tindzk** [comment]
Please reopen if this is still an issue.
