### ISSUE TITLE
onHover ?

### ISSUE THREAD

**Issue by freewind** [widok/widok#73]
For now I have to use `onMouseEnter` and `onMouseLeave` to implement jquery's `hover` function:

```
object Main extends PageApplication {
  val hovering = Var(false)

  def view() = span(
    h1("Welcome to Widok!"),
    div(
      p("Hover on this text ").onMouseEnter(_ => hovering := true).onMouseLeave(_ => hovering := false),
      span("hovered!").show(hovering)
    )
  )
}
```

Is it possible to provide a method like `onHover` that we can do:

```
p("...").onHover(hovering)
```

**Comment by jn73** [comment]
I think many use-cases involving hovering could be dealt with using css, right? Your case for example:

```html
<div id="container">
    <p>hover me!</p>
    <p class="visible-on-hover-parent">thanks for the hover</p>
</div>
```

and the css
```css
.visible-on-hover-parent {
  visibility: hidden;
}

#container:hover .visible-on-hover-parent {
  visibility: visible;
}
```

Since hover is a state I don't think it's a good fit for a callback. You would have to add a parameter indicating if it's a hover or "un-hover" and handle that in the callback.

Another way would be to add a isHovered: ReadChannel[Boolean] on the Widget

You can try adding this to the widget using implicits:

```scala
  implicit class WidgetSupport[A](widget: Widget[A]) {

    def isHovered = {
      val c = Channel[Boolean]()
      widget.onMouseEnter(e => c := true)
      widget.onMouseLeave(e => c := false)
      c.cache(false)
    }
}
```

Then you could add that boolean isHovered channel to conditionally show other widgets for example.

**Comment by freewind** [comment]
Thank you! Yes it's better to use CSS for my use case

**Comment by tindzk** [comment]
Thanks for your help, @jn73. I'd also go for the CSS solution.
